using Photon.Deterministic;

namespace Quantum
{
    [System.Serializable]
    public unsafe class GetPayloadDistance : AIFunction<FP>
    {
        public int TeamId;

        public override FP Execute(Frame frame, EntityRef entity, ref AIContext aiContext)
        {
            if(frame.Unsafe.TryGetPointer<Transform2D>(frame.Global->PayloadEntity, out var payloadTransform))
            {
                var allObjectivePoints = frame.Filter<PayloadObjectivePoint, Transform2D>();
                while (allObjectivePoints.NextUnsafe(out var objectivePointEntity, out var objectivePoint, out var transform))
                {
                    if (objectivePoint->TeamId == TeamId)
                    {
                        return FPVector2.DistanceSquared(payloadTransform->Position, transform->Position);
                    }
                }
            }

            return 42; // Randomly generated by a fair roll of dice
        }
    }
}